name: basic test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y freeglut3-dev mesa-common-dev libglu1-mesa-dev libgtest-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure